import Head from 'next/head'
import SearchBar from './searchBar'
import { Inter } from '@next/font/google'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          <p>
            Get started by editing&nbsp;
            <code>pages/index.tsx</code>
          </p>
        <SearchBar/>  
        </div>
      </main>
    </>
  )
}
